# Generated by Django 4.1.5 on 2023-06-10 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='achivement',
            name='photo',
            field=models.ImageField(null=True, upload_to='Achivement_img'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='photo',
            field=models.ImageField(null=True, upload_to='Project_img'),
        ),
        migrations.AlterField(
            model_name='project',
            name='photo',
            field=models.ImageField(null=True, upload_to='Project_img'),
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='photo',
            field=models.ImageField(null=True, upload_to='Testimonials_img'),
        ),
    ]
