# Generated by Django 4.1.5 on 2023-06-10 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_project_project_type_alter_achivement_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achivement',
            name='photo',
            field=models.ImageField(blank=True, upload_to='Achivement_img'),
        ),
    ]
