# Generated by Django 4.1.5 on 2023-06-10 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_blog_photo_alter_project_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='achivement',
            name='link',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
