# Generated by Django 4.1.5 on 2023-06-10 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_project_project_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='length',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
