# Generated by Django 4.1.5 on 2023-06-10 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_blog_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='url',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
