# Generated by Django 4.1.5 on 2023-06-10 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(blank=True, max_length=150)),
                ('name', models.CharField(blank=True, default='Mukerem Ali', max_length=150)),
                ('site', models.CharField(blank=True, max_length=50)),
                ('score', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
